CREATE OR REPLACE TABLE SILVER.CATEGORIES AS
SELECT
    CATEGORY_ID::NUMBER                          AS CATEGORY_ID,
    INITCAP(TRIM(CATEGORY_NAME))                 AS CATEGORY_NAME,
    PARENT_CATEGORY_ID::NUMBER                   AS PARENT_CATEGORY_ID,
    _LOADED_AT, _INGESTION_ID, _SOURCE_SYSTEM,
    CURRENT_TIMESTAMP()                          AS _PROCESSED_AT,
    {{ SILVER_RUN_ID }}                          AS _SILVER_RUN_ID
FROM BRONZE.CATEGORIES
QUALIFY ROW_NUMBER() OVER (PARTITION BY CATEGORY_ID ORDER BY _LOADED_AT DESC) = 1;
