CREATE OR REPLACE TABLE SILVER.INVENTORY AS
SELECT
    INVENTORY_ID::NUMBER                         AS INVENTORY_ID,
    PRODUCT_ID::NUMBER                           AS PRODUCT_ID,
    UPPER(TRIM(WAREHOUSE))                       AS WAREHOUSE,
    GREATEST(STOCK_QTY, 0)::NUMBER               AS STOCK_QTY,
    RESTOCK_DATE::DATE                           AS RESTOCK_DATE,
    _LOADED_AT, _INGESTION_ID, _SOURCE_SYSTEM,
    CURRENT_TIMESTAMP()                          AS _PROCESSED_AT,
    {{ SILVER_RUN_ID }}                          AS _SILVER_RUN_ID
FROM BRONZE.INVENTORY
QUALIFY ROW_NUMBER() OVER (PARTITION BY INVENTORY_ID ORDER BY _LOADED_AT DESC) = 1;
