CREATE OR REPLACE TABLE SILVER.MARKETING_CAMPAIGNS AS
SELECT
    CAMPAIGN_ID::NUMBER                          AS CAMPAIGN_ID,
    TRIM(CAMPAIGN_NAME)                          AS CAMPAIGN_NAME,
    INITCAP(TRIM(CHANNEL))                       AS CHANNEL,
    START_DATE::DATE                             AS START_DATE,
    END_DATE::DATE                               AS END_DATE,
    BUDGET::NUMBER(12,2)                         AS BUDGET,
    DATEDIFF(DAY, START_DATE, END_DATE)          AS DURATION_DAYS,
    _LOADED_AT, _INGESTION_ID, _SOURCE_SYSTEM,
    CURRENT_TIMESTAMP()                          AS _PROCESSED_AT,
    {{ SILVER_RUN_ID }}                          AS _SILVER_RUN_ID
FROM BRONZE.MARKETING_CAMPAIGNS
WHERE END_DATE >= START_DATE
QUALIFY ROW_NUMBER() OVER (PARTITION BY CAMPAIGN_ID ORDER BY _LOADED_AT DESC) = 1;
