CREATE OR REPLACE TABLE SILVER.PAYMENTS AS
SELECT
    PAYMENT_ID::NUMBER                           AS PAYMENT_ID,
    ORDER_ID::NUMBER                             AS ORDER_ID,
    PAYMENT_DATE::TIMESTAMP_NTZ                  AS PAYMENT_DATE,
    AMOUNT::NUMBER(12,2)                         AS AMOUNT,
    UPPER(TRIM(PAYMENT_STATUS))                  AS PAYMENT_STATUS,
    UPPER(TRIM(METHOD))                          AS METHOD,
    TRIM(TRANSACTION_ID)                         AS TRANSACTION_ID,
    _LOADED_AT, _INGESTION_ID, _SOURCE_SYSTEM,
    CURRENT_TIMESTAMP()                          AS _PROCESSED_AT,
    {{ SILVER_RUN_ID }}                          AS _SILVER_RUN_ID
FROM BRONZE.PAYMENTS
WHERE AMOUNT >= 0
QUALIFY ROW_NUMBER() OVER (PARTITION BY PAYMENT_ID ORDER BY _LOADED_AT DESC) = 1;
