CREATE OR REPLACE TABLE SILVER.RETURNS AS
SELECT
    RETURN_ID::NUMBER                            AS RETURN_ID,
    ORDER_ITEM_ID::NUMBER                        AS ORDER_ITEM_ID,
    RETURN_DATE::TIMESTAMP_NTZ                   AS RETURN_DATE,
    INITCAP(TRIM(REASON))                        AS REASON,
    GREATEST(REFUND_AMOUNT, 0)::NUMBER(10,2)     AS REFUND_AMOUNT,
    _LOADED_AT, _INGESTION_ID, _SOURCE_SYSTEM,
    CURRENT_TIMESTAMP()                          AS _PROCESSED_AT,
    {{ SILVER_RUN_ID }}                          AS _SILVER_RUN_ID
FROM BRONZE.RETURNS
QUALIFY ROW_NUMBER() OVER (PARTITION BY RETURN_ID ORDER BY _LOADED_AT DESC) = 1;
