CREATE OR REPLACE TABLE SILVER.REVIEWS AS
SELECT
    REVIEW_ID::NUMBER                            AS REVIEW_ID,
    ORDER_ID::NUMBER                             AS ORDER_ID,
    PRODUCT_ID::NUMBER                           AS PRODUCT_ID,
    CUSTOMER_ID::NUMBER                          AS CUSTOMER_ID,
    CASE WHEN RATING BETWEEN 1 AND 5 THEN RATING END AS RATING,
    TRIM(REVIEW_TEXT)                            AS REVIEW_TEXT,
    REVIEW_DATE::TIMESTAMP_NTZ                   AS REVIEW_DATE,
    _LOADED_AT, _INGESTION_ID, _SOURCE_SYSTEM,
    CURRENT_TIMESTAMP()                          AS _PROCESSED_AT,
    {{ SILVER_RUN_ID }}                          AS _SILVER_RUN_ID
FROM BRONZE.REVIEWS
WHERE RATING IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY REVIEW_ID ORDER BY _LOADED_AT DESC) = 1;
