CREATE OR REPLACE TABLE SILVER.SHIPMENTS AS
SELECT
    SHIPMENT_ID::NUMBER                                          AS SHIPMENT_ID,
    ORDER_ID::NUMBER                                             AS ORDER_ID,
    SHIPPED_DATE::TIMESTAMP_NTZ                                  AS SHIPPED_DATE,
    DELIVERY_DATE::TIMESTAMP_NTZ                                 AS DELIVERY_DATE,
    UPPER(TRIM(SHIPPING_STATUS))                                 AS SHIPPING_STATUS,
    GREATEST(SHIPPING_COST, 0)::NUMBER(10,2)                     AS SHIPPING_COST,
    INITCAP(TRIM(CARRIER))                                       AS CARRIER,
    CASE WHEN DELIVERY_DATE IS NOT NULL AND SHIPPED_DATE IS NOT NULL
         THEN DATEDIFF(DAY, SHIPPED_DATE, DELIVERY_DATE) END     AS DAYS_TO_DELIVER,
    _LOADED_AT, _INGESTION_ID, _SOURCE_SYSTEM,
    CURRENT_TIMESTAMP()                                          AS _PROCESSED_AT,
    {{ SILVER_RUN_ID }}                                          AS _SILVER_RUN_ID
FROM BRONZE.SHIPMENTS
WHERE DELIVERY_DATE IS NULL OR DELIVERY_DATE >= SHIPPED_DATE
QUALIFY ROW_NUMBER() OVER (PARTITION BY SHIPMENT_ID ORDER BY _LOADED_AT DESC) = 1;
