CREATE OR REPLACE TABLE SILVER.SUPPLIERS AS
SELECT
    SUPPLIER_ID::NUMBER                          AS SUPPLIER_ID,
    INITCAP(TRIM(SUPPLIER_NAME))                 AS SUPPLIER_NAME,
    INITCAP(TRIM(COUNTRY))                       AS COUNTRY,
    GREATEST(LEAD_TIME_DAYS, 0)::NUMBER          AS LEAD_TIME_DAYS,
    _LOADED_AT, _INGESTION_ID, _SOURCE_SYSTEM,
    CURRENT_TIMESTAMP()                          AS _PROCESSED_AT,
    {{ SILVER_RUN_ID }}                          AS _SILVER_RUN_ID
FROM BRONZE.SUPPLIERS
QUALIFY ROW_NUMBER() OVER (PARTITION BY SUPPLIER_ID ORDER BY _LOADED_AT DESC) = 1;
