CREATE SEQUENCE IF NOT EXISTS GOLD.SEQ_DIM_CUSTOMER START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS GOLD.SEQ_DIM_PRODUCT  START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS GOLD.SEQ_DIM_CAMPAIGN START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS GOLD.SEQ_DIM_COUPON   START = 1 INCREMENT = 1;
