CREATE TABLE IF NOT EXISTS GOLD.DIM_CAMPAIGN (
    CAMPAIGN_KEY   NUMBER        NOT NULL,
    CAMPAIGN_ID    NUMBER,
    CAMPAIGN_NAME  VARCHAR,
    CHANNEL        VARCHAR,
    START_DATE     DATE,
    END_DATE       DATE,
    BUDGET         NUMBER(12,2),
    DURATION_DAYS  NUMBER,
    _DIM_RUN_ID    VARCHAR,
    _UPDATED_AT    TIMESTAMP_NTZ
);

MERGE INTO GOLD.DIM_CAMPAIGN t
USING (SELECT -1 AS CAMPAIGN_KEY) s ON t.CAMPAIGN_KEY = s.CAMPAIGN_KEY
WHEN NOT MATCHED THEN INSERT
(CAMPAIGN_KEY, CAMPAIGN_ID, CAMPAIGN_NAME, CHANNEL, START_DATE, END_DATE, BUDGET, DURATION_DAYS, _DIM_RUN_ID, _UPDATED_AT)
VALUES (-1, NULL, 'Unknown', 'Unknown', NULL, NULL, NULL, NULL, {{ DIM_RUN_ID }}, CURRENT_TIMESTAMP());

MERGE INTO GOLD.DIM_CAMPAIGN t
USING SILVER.MARKETING_CAMPAIGNS s ON t.CAMPAIGN_ID = s.CAMPAIGN_ID
WHEN MATCHED THEN UPDATE SET
    CAMPAIGN_NAME = s.CAMPAIGN_NAME, CHANNEL = s.CHANNEL,
    START_DATE = s.START_DATE, END_DATE = s.END_DATE,
    BUDGET = s.BUDGET, DURATION_DAYS = s.DURATION_DAYS,
    _DIM_RUN_ID = {{ DIM_RUN_ID }}, _UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
(CAMPAIGN_KEY, CAMPAIGN_ID, CAMPAIGN_NAME, CHANNEL, START_DATE, END_DATE, BUDGET, DURATION_DAYS, _DIM_RUN_ID, _UPDATED_AT)
VALUES (GOLD.SEQ_DIM_CAMPAIGN.NEXTVAL, s.CAMPAIGN_ID, s.CAMPAIGN_NAME, s.CHANNEL,
        s.START_DATE, s.END_DATE, s.BUDGET, s.DURATION_DAYS, {{ DIM_RUN_ID }}, CURRENT_TIMESTAMP());
