CREATE TABLE IF NOT EXISTS GOLD.DIM_COUPON (
    COUPON_KEY     NUMBER        NOT NULL,
    COUPON_ID      NUMBER,
    CODE           VARCHAR,
    DISCOUNT_TYPE  VARCHAR,
    DISCOUNT_VALUE NUMBER(10,2),
    START_DATE     DATE,
    END_DATE       DATE,
    _DIM_RUN_ID    VARCHAR,
    _UPDATED_AT    TIMESTAMP_NTZ
);

MERGE INTO GOLD.DIM_COUPON t
USING (SELECT -1 AS COUPON_KEY) s ON t.COUPON_KEY = s.COUPON_KEY
WHEN NOT MATCHED THEN INSERT
(COUPON_KEY, COUPON_ID, CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, START_DATE, END_DATE, _DIM_RUN_ID, _UPDATED_AT)
VALUES (-1, NULL, 'Unknown', 'Unknown', NULL, NULL, NULL, {{ DIM_RUN_ID }}, CURRENT_TIMESTAMP());

MERGE INTO GOLD.DIM_COUPON t
USING SILVER.COUPONS s ON t.COUPON_ID = s.COUPON_ID
WHEN MATCHED THEN UPDATE SET
    CODE = s.CODE, DISCOUNT_TYPE = s.DISCOUNT_TYPE, DISCOUNT_VALUE = s.DISCOUNT_VALUE,
    START_DATE = s.START_DATE, END_DATE = s.END_DATE,
    _DIM_RUN_ID = {{ DIM_RUN_ID }}, _UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
(COUPON_KEY, COUPON_ID, CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, START_DATE, END_DATE, _DIM_RUN_ID, _UPDATED_AT)
VALUES (GOLD.SEQ_DIM_COUPON.NEXTVAL, s.COUPON_ID, s.CODE, s.DISCOUNT_TYPE,
        s.DISCOUNT_VALUE, s.START_DATE, s.END_DATE, {{ DIM_RUN_ID }}, CURRENT_TIMESTAMP());
