CREATE TABLE IF NOT EXISTS GOLD.DIM_CUSTOMER (
    CUSTOMER_KEY   NUMBER        NOT NULL,
    CUSTOMER_ID    NUMBER,
    FIRST_NAME     VARCHAR,
    LAST_NAME      VARCHAR,
    FULL_NAME      VARCHAR,
    EMAIL          VARCHAR,
    CITY           VARCHAR,
    STATE          VARCHAR,
    COUNTRY        VARCHAR,
    AGE            NUMBER,
    AGE_BAND       VARCHAR,
    GENDER         VARCHAR,
    SIGNUP_DATE    DATE,
    ROW_HASH       VARCHAR,
    VALID_FROM     TIMESTAMP_NTZ,
    VALID_TO       TIMESTAMP_NTZ,
    IS_CURRENT     BOOLEAN,
    _DIM_RUN_ID    VARCHAR
);

MERGE INTO GOLD.DIM_CUSTOMER t
USING (SELECT -1 AS CUSTOMER_KEY) s ON t.CUSTOMER_KEY = s.CUSTOMER_KEY
WHEN NOT MATCHED THEN INSERT
(CUSTOMER_KEY, CUSTOMER_ID, FIRST_NAME, LAST_NAME, FULL_NAME, EMAIL, CITY, STATE, COUNTRY,
 AGE, AGE_BAND, GENDER, SIGNUP_DATE, ROW_HASH, VALID_FROM, VALID_TO, IS_CURRENT, _DIM_RUN_ID)
VALUES (-1, NULL, 'Unknown', 'Unknown', 'Unknown', NULL, 'Unknown', 'Unknown', 'Unknown',
        NULL, 'Unknown', 'Unknown', NULL, 'UNKNOWN', '1900-01-01'::TIMESTAMP_NTZ, NULL, TRUE, {{ DIM_RUN_ID }});

CREATE OR REPLACE VIEW GOLD.STG_DIM_CUSTOMER AS
SELECT
    CUSTOMER_ID, FIRST_NAME, LAST_NAME,
    FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
    EMAIL, CITY, STATE, COUNTRY, AGE,
    CASE
        WHEN AGE IS NULL THEN 'Unknown'
        WHEN AGE < 25    THEN '18-24'
        WHEN AGE < 35    THEN '25-34'
        WHEN AGE < 45    THEN '35-44'
        WHEN AGE < 55    THEN '45-54'
        WHEN AGE < 65    THEN '55-64'
        ELSE '65+'
    END AS AGE_BAND,
    GENDER, SIGNUP_DATE,
    MD5(
        COALESCE(FIRST_NAME,'') || '|' || COALESCE(LAST_NAME,'') || '|' ||
        COALESCE(EMAIL,'')      || '|' || COALESCE(CITY,'')      || '|' ||
        COALESCE(STATE,'')      || '|' || COALESCE(COUNTRY,'')   || '|' ||
        COALESCE(TO_VARCHAR(AGE),'') || '|' || COALESCE(GENDER,'')
    ) AS ROW_HASH
FROM SILVER.CUSTOMERS;

UPDATE GOLD.DIM_CUSTOMER d
SET VALID_TO = CURRENT_TIMESTAMP(), IS_CURRENT = FALSE
FROM GOLD.STG_DIM_CUSTOMER s
WHERE d.CUSTOMER_ID = s.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE
  AND d.ROW_HASH <> s.ROW_HASH;

INSERT INTO GOLD.DIM_CUSTOMER
(CUSTOMER_KEY, CUSTOMER_ID, FIRST_NAME, LAST_NAME, FULL_NAME, EMAIL, CITY, STATE, COUNTRY,
 AGE, AGE_BAND, GENDER, SIGNUP_DATE, ROW_HASH, VALID_FROM, VALID_TO, IS_CURRENT, _DIM_RUN_ID)
SELECT
    GOLD.SEQ_DIM_CUSTOMER.NEXTVAL, s.CUSTOMER_ID, s.FIRST_NAME, s.LAST_NAME, s.FULL_NAME,
    s.EMAIL, s.CITY, s.STATE, s.COUNTRY, s.AGE, s.AGE_BAND, s.GENDER, s.SIGNUP_DATE, s.ROW_HASH,
    CASE WHEN EXISTS (SELECT 1 FROM GOLD.DIM_CUSTOMER d2 WHERE d2.CUSTOMER_ID = s.CUSTOMER_ID)
         THEN CURRENT_TIMESTAMP()
         ELSE '1900-01-01'::TIMESTAMP_NTZ END,
    NULL, TRUE, {{ DIM_RUN_ID }}
FROM GOLD.STG_DIM_CUSTOMER s
LEFT JOIN GOLD.DIM_CUSTOMER d
    ON s.CUSTOMER_ID = d.CUSTOMER_ID AND d.IS_CURRENT = TRUE
WHERE d.CUSTOMER_KEY IS NULL;