CREATE TABLE IF NOT EXISTS GOLD.DIM_PRODUCT (
    PRODUCT_KEY      NUMBER       NOT NULL,
    PRODUCT_ID       NUMBER,
    PRODUCT_NAME     VARCHAR,
    CATEGORY_ID      NUMBER,
    CATEGORY_NAME    VARCHAR,
    PARENT_CATEGORY  VARCHAR,
    BRAND            VARCHAR,
    SUPPLIER_ID      NUMBER,
    SUPPLIER_NAME    VARCHAR,
    SUPPLIER_COUNTRY VARCHAR,
    UNIT_PRICE       NUMBER(10,2),
    COST             NUMBER(10,2),
    UNIT_MARGIN      NUMBER(10,2),
    ROW_HASH         VARCHAR,
    VALID_FROM       TIMESTAMP_NTZ,
    VALID_TO         TIMESTAMP_NTZ,
    IS_CURRENT       BOOLEAN,
    _DIM_RUN_ID      VARCHAR
);

MERGE INTO GOLD.DIM_PRODUCT t
USING (SELECT -1 AS PRODUCT_KEY) s ON t.PRODUCT_KEY = s.PRODUCT_KEY
WHEN NOT MATCHED THEN INSERT
(PRODUCT_KEY, PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, CATEGORY_NAME, PARENT_CATEGORY, BRAND,
 SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_COUNTRY, UNIT_PRICE, COST, UNIT_MARGIN,
 ROW_HASH, VALID_FROM, VALID_TO, IS_CURRENT, _DIM_RUN_ID)
VALUES (-1, NULL, 'Unknown', NULL, 'Unknown', 'Unknown', 'Unknown', NULL, 'Unknown', 'Unknown',
        NULL, NULL, NULL, 'UNKNOWN', '1900-01-01'::TIMESTAMP_NTZ, NULL, TRUE, {{ DIM_RUN_ID }});

CREATE OR REPLACE VIEW GOLD.STG_DIM_PRODUCT AS
SELECT
    p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY_ID,
    c.CATEGORY_NAME, pc.CATEGORY_NAME AS PARENT_CATEGORY,
    p.BRAND, p.SUPPLIER_ID, s.SUPPLIER_NAME, s.COUNTRY AS SUPPLIER_COUNTRY,
    p.UNIT_PRICE, p.COST, p.UNIT_MARGIN,
    MD5(
        COALESCE(p.PRODUCT_NAME,'')           || '|' || COALESCE(c.CATEGORY_NAME,'') || '|' ||
        COALESCE(p.BRAND,'')                  || '|' || COALESCE(s.SUPPLIER_NAME,'') || '|' ||
        COALESCE(TO_VARCHAR(p.UNIT_PRICE),'') || '|' || COALESCE(TO_VARCHAR(p.COST),'')
    ) AS ROW_HASH
FROM SILVER.PRODUCTS p
LEFT JOIN SILVER.CATEGORIES c  ON p.CATEGORY_ID = c.CATEGORY_ID
LEFT JOIN SILVER.CATEGORIES pc ON c.PARENT_CATEGORY_ID = pc.CATEGORY_ID
LEFT JOIN SILVER.SUPPLIERS s   ON p.SUPPLIER_ID = s.SUPPLIER_ID;

UPDATE GOLD.DIM_PRODUCT d
SET VALID_TO = CURRENT_TIMESTAMP(), IS_CURRENT = FALSE
FROM GOLD.STG_DIM_PRODUCT s
WHERE d.PRODUCT_ID = s.PRODUCT_ID
  AND d.IS_CURRENT = TRUE
  AND d.ROW_HASH <> s.ROW_HASH;

INSERT INTO GOLD.DIM_PRODUCT
(PRODUCT_KEY, PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, CATEGORY_NAME, PARENT_CATEGORY, BRAND,
 SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_COUNTRY, UNIT_PRICE, COST, UNIT_MARGIN,
 ROW_HASH, VALID_FROM, VALID_TO, IS_CURRENT, _DIM_RUN_ID)
SELECT
    GOLD.SEQ_DIM_PRODUCT.NEXTVAL, s.PRODUCT_ID, s.PRODUCT_NAME, s.CATEGORY_ID, s.CATEGORY_NAME,
    s.PARENT_CATEGORY, s.BRAND, s.SUPPLIER_ID, s.SUPPLIER_NAME, s.SUPPLIER_COUNTRY,
    s.UNIT_PRICE, s.COST, s.UNIT_MARGIN, s.ROW_HASH,
    CASE WHEN EXISTS (SELECT 1 FROM GOLD.DIM_PRODUCT d2 WHERE d2.PRODUCT_ID = s.PRODUCT_ID)
         THEN CURRENT_TIMESTAMP()
         ELSE '1900-01-01'::TIMESTAMP_NTZ END,
    NULL, TRUE, {{ DIM_RUN_ID }}
FROM GOLD.STG_DIM_PRODUCT s
LEFT JOIN GOLD.DIM_PRODUCT d
    ON s.PRODUCT_ID = d.PRODUCT_ID AND d.IS_CURRENT = TRUE
WHERE d.PRODUCT_KEY IS NULL;