CREATE OR REPLACE TABLE GOLD.FACT_PAYMENTS AS
SELECT
    p.PAYMENT_ID,
    p.ORDER_ID,
    p.TRANSACTION_ID,
    COALESCE(dd.DATE_KEY, -1)     AS DATE_KEY,
    COALESCE(dc.CUSTOMER_KEY, -1) AS CUSTOMER_KEY,
    p.AMOUNT,
    p.PAYMENT_STATUS,
    p.METHOD AS PAYMENT_METHOD,
    p.PAYMENT_DATE,
    CURRENT_TIMESTAMP() AS _FACT_LOADED_AT,
    {{ FACT_RUN_ID }}   AS _FACT_RUN_ID
FROM SILVER.PAYMENTS p
JOIN SILVER.ORDERS o          ON p.ORDER_ID = o.ORDER_ID
LEFT JOIN GOLD.DIM_DATE dd    ON TO_NUMBER(TO_CHAR(p.PAYMENT_DATE, 'YYYYMMDD')) = dd.DATE_KEY
LEFT JOIN GOLD.DIM_CUSTOMER dc ON o.CUSTOMER_ID = dc.CUSTOMER_ID
                              AND p.PAYMENT_DATE >= dc.VALID_FROM
                              AND p.PAYMENT_DATE <  COALESCE(dc.VALID_TO, '9999-12-31'::TIMESTAMP_NTZ);
