CREATE OR REPLACE TABLE GOLD.FACT_SHIPMENTS AS
SELECT
    sh.SHIPMENT_ID,
    sh.ORDER_ID,
    COALESCE(dd.DATE_KEY, -1)     AS DATE_KEY,
    COALESCE(dc.CUSTOMER_KEY, -1) AS CUSTOMER_KEY,
    sh.SHIPPING_STATUS,
    sh.CARRIER,
    sh.SHIPPING_COST,
    sh.DAYS_TO_DELIVER,
    sh.SHIPPED_DATE,
    sh.DELIVERY_DATE,
    CURRENT_TIMESTAMP() AS _FACT_LOADED_AT,
    {{ FACT_RUN_ID }}   AS _FACT_RUN_ID
FROM SILVER.SHIPMENTS sh
JOIN SILVER.ORDERS o          ON sh.ORDER_ID = o.ORDER_ID
LEFT JOIN GOLD.DIM_DATE dd    ON TO_NUMBER(TO_CHAR(sh.SHIPPED_DATE, 'YYYYMMDD')) = dd.DATE_KEY
LEFT JOIN GOLD.DIM_CUSTOMER dc ON o.CUSTOMER_ID = dc.CUSTOMER_ID
                              AND sh.SHIPPED_DATE >= dc.VALID_FROM
                              AND sh.SHIPPED_DATE <  COALESCE(dc.VALID_TO, '9999-12-31'::TIMESTAMP_NTZ);
