CREATE OR REPLACE TABLE GOLD.FACT_RETURNS AS
SELECT
    r.RETURN_ID,
    r.ORDER_ITEM_ID,
    oi.ORDER_ID,
    COALESCE(dd.DATE_KEY, -1)     AS DATE_KEY,
    COALESCE(dc.CUSTOMER_KEY, -1) AS CUSTOMER_KEY,
    COALESCE(dp.PRODUCT_KEY, -1)  AS PRODUCT_KEY,
    r.REASON,
    r.REFUND_AMOUNT,
    r.RETURN_DATE,
    CURRENT_TIMESTAMP() AS _FACT_LOADED_AT,
    {{ FACT_RUN_ID }}   AS _FACT_RUN_ID
FROM SILVER.RETURNS r
JOIN SILVER.ORDER_ITEMS oi    ON r.ORDER_ITEM_ID = oi.ORDER_ITEM_ID
JOIN SILVER.ORDERS o          ON oi.ORDER_ID = o.ORDER_ID
LEFT JOIN GOLD.DIM_DATE dd    ON TO_NUMBER(TO_CHAR(r.RETURN_DATE, 'YYYYMMDD')) = dd.DATE_KEY
LEFT JOIN GOLD.DIM_CUSTOMER dc ON o.CUSTOMER_ID = dc.CUSTOMER_ID
                              AND r.RETURN_DATE >= dc.VALID_FROM
                              AND r.RETURN_DATE <  COALESCE(dc.VALID_TO, '9999-12-31'::TIMESTAMP_NTZ)
LEFT JOIN GOLD.DIM_PRODUCT dp  ON oi.PRODUCT_ID = dp.PRODUCT_ID
                              AND r.RETURN_DATE >= dp.VALID_FROM
                              AND r.RETURN_DATE <  COALESCE(dp.VALID_TO, '9999-12-31'::TIMESTAMP_NTZ);
