CREATE OR REPLACE TABLE GOLD.FACT_REVIEWS AS
SELECT
    rv.REVIEW_ID,
    rv.ORDER_ID,
    COALESCE(dd.DATE_KEY, -1)     AS DATE_KEY,
    COALESCE(dc.CUSTOMER_KEY, -1) AS CUSTOMER_KEY,
    COALESCE(dp.PRODUCT_KEY, -1)  AS PRODUCT_KEY,
    rv.RATING,
    rv.REVIEW_DATE,
    CURRENT_TIMESTAMP() AS _FACT_LOADED_AT,
    {{ FACT_RUN_ID }}   AS _FACT_RUN_ID
FROM SILVER.REVIEWS rv
LEFT JOIN GOLD.DIM_DATE dd     ON TO_NUMBER(TO_CHAR(rv.REVIEW_DATE, 'YYYYMMDD')) = dd.DATE_KEY
LEFT JOIN GOLD.DIM_CUSTOMER dc ON rv.CUSTOMER_ID = dc.CUSTOMER_ID
                              AND rv.REVIEW_DATE >= dc.VALID_FROM
                              AND rv.REVIEW_DATE <  COALESCE(dc.VALID_TO, '9999-12-31'::TIMESTAMP_NTZ)
LEFT JOIN GOLD.DIM_PRODUCT dp  ON rv.PRODUCT_ID = dp.PRODUCT_ID
                              AND rv.REVIEW_DATE >= dp.VALID_FROM
                              AND rv.REVIEW_DATE <  COALESCE(dp.VALID_TO, '9999-12-31'::TIMESTAMP_NTZ);
