CREATE OR REPLACE TABLE GOLD.FACT_WEB_SESSIONS AS
SELECT
    ws.SESSION_ID,
    COALESCE(dd.DATE_KEY, -1)       AS DATE_KEY,
    COALESCE(dc.CUSTOMER_KEY, -1)   AS CUSTOMER_KEY,
    COALESCE(dcam.CAMPAIGN_KEY, -1) AS CAMPAIGN_KEY,
    ws.SOURCE,
    ws.MEDIUM,
    ws.DEVICE,
    ws.SESSION_DURATION_SEC,
    ws.SESSION_START,
    CURRENT_TIMESTAMP() AS _FACT_LOADED_AT,
    {{ FACT_RUN_ID }}   AS _FACT_RUN_ID
FROM SILVER.WEB_SESSIONS ws
LEFT JOIN GOLD.DIM_DATE dd     ON TO_NUMBER(TO_CHAR(ws.SESSION_START, 'YYYYMMDD')) = dd.DATE_KEY
LEFT JOIN GOLD.DIM_CUSTOMER dc ON ws.CUSTOMER_ID = dc.CUSTOMER_ID
                              AND ws.SESSION_START >= dc.VALID_FROM
                              AND ws.SESSION_START <  COALESCE(dc.VALID_TO, '9999-12-31'::TIMESTAMP_NTZ)
LEFT JOIN GOLD.DIM_CAMPAIGN dcam ON ws.CAMPAIGN_ID = dcam.CAMPAIGN_ID;
