CREATE OR REPLACE VIEW GOLD.VW_PIPELINE_RUNS AS
SELECT 'BRONZE' AS LAYER, INGESTION_ID AS RUN_ID, TABLE_NAME AS OBJECT_NAME,
       STARTED_AT, ENDED_AT, ROWS_LOADED AS ROW_COUNT, STATUS, ERROR_MESSAGE
FROM BRONZE._INGESTION_LOG
UNION ALL
SELECT 'SILVER', SILVER_RUN_ID, TABLE_NAME, STARTED_AT, ENDED_AT, ROW_COUNT, STATUS, ERROR_MESSAGE
FROM SILVER._SILVER_RUN_LOG
UNION ALL
SELECT 'GOLD', GOLD_RUN_ID, OBJECT_NAME, STARTED_AT, ENDED_AT, ROW_COUNT, STATUS, ERROR_MESSAGE
FROM GOLD._GOLD_RUN_LOG;
