CREATE OR REPLACE VIEW GOLD.VW_SALES_DETAIL AS
SELECT
    f.ORDER_ITEM_ID, f.ORDER_ID,
    d.FULL_DATE, d.YEAR, d.QUARTER, d.MONTH_NUM, d.MONTH_NAME, d.YEAR_MONTH, d.IS_WEEKEND,
    c.CUSTOMER_ID, c.FULL_NAME AS CUSTOMER_NAME, c.CITY, c.STATE, c.COUNTRY, c.AGE_BAND, c.GENDER,
    p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY_NAME, p.BRAND, p.SUPPLIER_NAME,
    cam.CAMPAIGN_NAME, cam.CHANNEL,
    cp.CODE AS COUPON_CODE, cp.DISCOUNT_TYPE,
    f.QUANTITY, f.GROSS_REVENUE, f.DISCOUNT_AMT, f.TAX_AMT,
    f.NET_REVENUE, f.COST_AMT, f.GROSS_MARGIN
FROM GOLD.FACT_SALES f
JOIN GOLD.DIM_DATE d       ON f.DATE_KEY = d.DATE_KEY
JOIN GOLD.DIM_CUSTOMER c   ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN GOLD.DIM_PRODUCT p    ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN GOLD.DIM_CAMPAIGN cam ON f.CAMPAIGN_KEY = cam.CAMPAIGN_KEY
JOIN GOLD.DIM_COUPON cp    ON f.COUPON_KEY = cp.COUPON_KEY;
