CREATE OR REPLACE VIEW GOLD.VW_CUSTOMER_360 AS
WITH sales AS (
    SELECT dc.CUSTOMER_ID,
           COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
           SUM(f.NET_REVENUE)         AS TOTAL_REVENUE,
           SUM(f.GROSS_MARGIN)        AS TOTAL_MARGIN,
           MIN(f.ORDER_DATE)          AS FIRST_ORDER_DATE,
           MAX(f.ORDER_DATE)          AS LAST_ORDER_DATE
    FROM GOLD.FACT_SALES f
    JOIN GOLD.DIM_CUSTOMER dc ON f.CUSTOMER_KEY = dc.CUSTOMER_KEY
    GROUP BY dc.CUSTOMER_ID
),
ret AS (
    SELECT dc.CUSTOMER_ID, COUNT(*) AS TOTAL_RETURNS, SUM(f.REFUND_AMOUNT) AS TOTAL_REFUNDS
    FROM GOLD.FACT_RETURNS f
    JOIN GOLD.DIM_CUSTOMER dc ON f.CUSTOMER_KEY = dc.CUSTOMER_KEY
    GROUP BY dc.CUSTOMER_ID
),
rev AS (
    SELECT dc.CUSTOMER_ID, COUNT(*) AS TOTAL_REVIEWS, AVG(f.RATING) AS AVG_RATING
    FROM GOLD.FACT_REVIEWS f
    JOIN GOLD.DIM_CUSTOMER dc ON f.CUSTOMER_KEY = dc.CUSTOMER_KEY
    GROUP BY dc.CUSTOMER_ID
)
SELECT
    c.CUSTOMER_ID, c.FULL_NAME, c.EMAIL, c.CITY, c.STATE, c.COUNTRY,
    c.AGE_BAND, c.GENDER, c.SIGNUP_DATE,
    COALESCE(s.TOTAL_ORDERS, 0)   AS TOTAL_ORDERS,
    COALESCE(s.TOTAL_REVENUE, 0)  AS TOTAL_REVENUE,
    COALESCE(s.TOTAL_MARGIN, 0)   AS TOTAL_MARGIN,
    s.FIRST_ORDER_DATE, s.LAST_ORDER_DATE,
    COALESCE(r.TOTAL_RETURNS, 0)  AS TOTAL_RETURNS,
    COALESCE(r.TOTAL_REFUNDS, 0)  AS TOTAL_REFUNDS,
    COALESCE(rv.TOTAL_REVIEWS, 0) AS TOTAL_REVIEWS,
    rv.AVG_RATING
FROM GOLD.DIM_CUSTOMER c
LEFT JOIN sales s ON c.CUSTOMER_ID = s.CUSTOMER_ID
LEFT JOIN ret r   ON c.CUSTOMER_ID = r.CUSTOMER_ID
LEFT JOIN rev rv  ON c.CUSTOMER_ID = rv.CUSTOMER_ID
WHERE c.IS_CURRENT = TRUE AND c.CUSTOMER_KEY <> -1;
